#!/bin/bash

host="$1"
file="/var/www/$1"

function createHost {
	sudo mkdir -p $file
	sudo chmod 777 $file -R

	sudo cp "/etc/nginx/sites-available/default" "/etc/nginx/sites-available/$host"
	sudo ln -s "/etc/nginx/sites-available/$host" "/etc/nginx/sites-enabled/"
#удалить из файла sites-avail и заменить хост - sed
#добавить в файл /etc/hosts

	sudo service nginx restart
}

if createHost
	then
		echo "Хост \"$host\" был успешно создан."
	else
		echo "Ошибка!"
fi